### ISSUE TITLE
Add Function is completely buggy

### ISSUE THREAD

**Issue by thienhoang23** [UCSB-CS56-Projects/cs56-utilities-restaurant-list#12]
When adding a new restaurant with a new cuisine, the cuisine is added but not the restaurant.
When adding a new restaurant to an old cuisine, the restaurant is not added.

**Comment by EasterAndJay** [comment]
200 points

**Comment by thienhoang23** [comment]
Brenda actually meant #10

**Comment by EasterAndJay** [comment]
Closed
