### ISSUE TITLE
AddNew Function Error when adding an empty (meaningless) Restaurant

### ISSUE THREAD

**Issue by thienhoang23** [UCSB-CS56-Projects/cs56-utilities-restaurant-list#14]
AddNew allows users to add a restaurant that has NULL for field, i.e. all the fields in AddNew are empty. After submit such restaurant, the program becomes completely useless and could not display any restaurants even though the cuisines are displayed.

**Comment by EasterAndJay** [comment]
Estimated 100 points

**Comment by EasterAndJay** [comment]
Closed
