### ISSUE TITLE
Second API for Operation Hours

### ISSUE THREAD

**Issue by thienhoang23** [UCSB-CS56-Projects/cs56-utilities-restaurant-list#17]
Because YELP API does not provide the hours of operations, you should look for a second API that could cross reference with the YELP API and enhance the usability of the program.

**Comment by EasterAndJay** [comment]
W16 approved

**Comment by dlynch305** [comment]
400pts

**Comment by jmangel** [comment]
The Google Place API may be a possible tool for this. https://developers.google.com/places/web-service/details#PlaceDetailsResults

**Comment by jmangel** [comment]
F16 OK (300 pts)

**Comment by jmangel** [comment]
Closing with pull request #43
