### ISSUE TITLE
Reviews/ Rating

### ISSUE THREAD

**Issue by thienhoang23** [UCSB-CS56-Projects/cs56-utilities-restaurant-list#18]
Use Yelp API to pull the reviews and ratings

**Comment by EasterAndJay** [comment]
Approved W16

**Comment by dlynch305** [comment]
200pts

**Comment by timnkwong** [comment]
Pull ratings only for 100 points?

**Comment by jmangel** [comment]
Ratings are currently being pulled but not displayed.

**Comment by jmangel** [comment]
F16 OK (150 pts)

**Comment by jmangel** [comment]
Closing with pull request #43
