### ISSUE TITLE
Fix directory structure

### ISSUE THREAD

**Issue by dlynch305** [UCSB-CS56-Projects/cs56-utilities-restaurant-list#19]
Make it more intuitive. It's a mess.

~50 pts

**Comment by alanthetran** [comment]
https://github.com/alanthetran/cs56-utilities-restaurant-list/commit/86ac587eb74819658f2292880dcb11f01988fa6b
https://github.com/alanthetran/cs56-utilities-restaurant-list/commit/5d7e12b30b096c4f2c26a5218b9ec01210d77158
Fixed directory structure.

**Comment by dlynch305** [comment]
Solved M16
