### ISSUE TITLE
INVALID_SIGNATURE error. 150 pts

### ISSUE THREAD

**Issue by jmangel** [ucsb-cs56-projects/cs56-utilities-restaurant-list#37]
This rare bug can be reproduced by searching for Mexican restaurants in "California". The terminal will show that this error was thrown on querying "casa-la-doña-los-angeles-2", saying that the oauth_signature was invalid. My only lead is that it may have something to do with the special character 'ñ' in the restaurant name.

**Comment by jmangel** [comment]
F16 OK (100 pts)

**Comment by john-lau** [comment]
W18 OK. 100 pts

**Comment by dannycho7** [comment]
Finished

**Comment by john-lau** [comment]
closed with pull request #59
