### ISSUE TITLE
Move generated javadoc location to github-pages. 50 pts

### ISSUE THREAD

**Issue by jmangel** [ucsb-cs56-projects/cs56-utilities-restaurant-list#38]
build.xml currently publishes the javadoc to a CSIL account
Instead, use the github-pages workflow to publish your javadoc to a github pages URL

**Comment by jmangel** [comment]
F16 OK (100 pts)

**Comment by john-lau** [comment]
W18 OK. 50 pts

**Comment by john-lau** [comment]
closed with pull request #59
