### ISSUE TITLE
Add navigation buttons to Reviews window. 25 pts

### ISSUE THREAD

**Issue by jmangel** [ucsb-cs56-projects/cs56-utilities-restaurant-list#45]
Since this opens as a separate window, even just a close button is OK (not all GUI clients show the minimize, maximize, close button in the corner); feel free to create any other buttons you think would be useful.

**Comment by jmangel** [comment]
F16 OK (25 pts)

**Comment by john-lau** [comment]
W18 OK. 25 pts

**Comment by DennisZZH** [comment]
Issue #45 done. Petition to raise issue#45 to 50 pts.
Reason1: this issue took similar amount of time to fix as previous 50 pts issues.
Reason2: All the other issues worth multiple of 50. Bumping issue#45 would help us better get useful points.

**Comment by john-lau** [comment]
closed with pull request #61
