### ISSUE TITLE
GUI code Refactoring. 500 pts

### ISSUE THREAD

**Issue by N7Alpha** [ucsb-cs56-projects/cs56-utilities-restaurant-list#51]
Migrate the different UI's from GuiUserInput to their own panel classes like the main screen, eatscreen, etc. Name them something like eatPanel, mainMenuPanel etc. and consolidate some of the duplicate code in the program specifically the from the showFutureChoice and EatScreen methods.
600 Points

**Comment by john-lau** [comment]
W18 OK. 600 pts

**Comment by john-lau** [comment]
closed with pull request #61
