### ISSUE TITLE
Use specific day's business hours for future time. 100 pts

### ISSUE THREAD

**Issue by jmangel** [ucsb-cs56-projects/cs56-utilities-restaurant-list#53]
When searching for a restaurant at a future time, the restaurant's generic startTime and endTime are used, rather than the collection of daily hours that is now accessible.

Estimated 100

**Comment by john-lau** [comment]
W18 OK. 100 pts

**Comment by dannycho7** [comment]
Finished

**Comment by john-lau** [comment]
closed with pull request #59
