### ISSUE TITLE
Move Yelp API keys to hidden environment variables

### ISSUE THREAD

**Issue by dannycho7** [ucsb-cs56-projects/cs56-utilities-restaurant-list#57]
Currently, the Yelp API keys (private passwords!) are checked in to the github repository. We also recently ran into an issue of hitting the API limit.
![image](https://user-images.githubusercontent.com/15878248/36575940-87065a8c-1802-11e8-83de-981494f0a51a.png)

Our proposed solution is to move the API keys to an environment variable that is not checked in to the central repository (or any repository)

**Comment by dannycho7** [comment]
Finished

**Comment by john-lau** [comment]
closed with pull request #59
