### ISSUE TITLE
Back from menu screen to the privious retaurant screen

### ISSUE THREAD

**Issue by DennisZZH** [ucsb-cs56-projects/cs56-utilities-restaurant-list#62]
When users finishing viewing the menu screen and hit back button, they would return to the main screen instead the previous selected restaurant screen, which would cause inconvenience if users still want to view the restaurant. Make the back button do the job that return to the previous selected restaurant screen when clicked.  50 pts. #

**Comment by DennisZZH** [comment]
Also, make the menu screen a "pop out window" would be better. ( same as review window).

**Comment by john-lau** [comment]
closed with pull request #61
